fields:
  - {name: id, type: utf8, nullable: true}
  - {name: name, type: utf8, nullable: true}
  - {name: category, type: utf8, nullable: true}
  - {name: subcategory, type: utf8, nullable: true}
  - {name: base_price, type: float64, nullable: true}
  - {name: cost, type: float64, nullable: true}
  - {name: in_stock, type: int64, nullable: true}
  - {name: supplier_id, type: int64, nullable: true}
  - name: created_at
    type:
      timestamp: {unit: ns}
    nullable: true
  - {name: is_active, type: boolean, nullable: true}
